INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

INSERT INTO review_score(ACT_NUMBER, HOTEL, COUNT_ALL, REV_AVG, COUNT5, COUNT4, COUNT3, COUNT2, COUNT1)
VALUES (SEQ_REVSC_NUM.nextval, 'test', 0, 0, 0, 0, 0, 0, 0);

commit;